feat!: include API version in HTTP service URL scheme
- the file imported on the client to reference the API versions is updated
to include all providers, rather than just the root version.
- consumers of cardano-services-client no longer need to provide the service slug

diff --git a/.github/workflows/continuous-integration-unit-tests.yaml b/.github/workflows/continuous-integration-unit-tests.yaml
--- a/.github/workflows/continuous-integration-unit-tests.yaml
+++ b/.github/workflows/continuous-integration-unit-tests.yaml
@@ -30,6 +30,10 @@ jobs:
       run: |
         yarn install --immutable --inline-builds
         yarn build
+
+    - name: 🔨 Generated files
+      run: |
+        if [ ! -z "$(git status --porcelain)" ] ; then git status ; echo "The PR is missing some generated file" ; exit 1 ; fi
         yarn lint
 
     - name: 🔃 Check for circular dependencies
